### ISSUE TITLE
Doesn't seem to work at all on Twitter.

### ISSUE THREAD

**Issue by shipbrook** [jkingsman/regex-replace#12]
Replacements that work well on other sites don't work on Twitter (either on the Twitter website, or in tweets embedded on other pages).

I've tried it both with Twitter added "On specific sites" (supplying both http and https, with and without www) and "On all sites".

**Comment by jkingsman** [comment]
Sadly this does not work well with dynamic rendering, so this will not be able to be supported.

Sorry for the delay in response!
