### ISSUE TITLE
Duplication when replacement contains original string

### ISSUE THREAD

**Issue by jpeterbaker** [jkingsman/regex-replace#2]
It seems that when the replacement string matches the search, the substitution gets applied twice. The rule
`donut --> pink donut`
performs the substitution
`donut --> pink pink donut`.

As a workaround, I'm using
`gibberish1 --> gibberish2`
`donut --> gibberish1`
`gibberish2 --> pink donut`
which does in fact perform the subsitution `donut --> pink donut` because all the substitutions are done in order twice.

I'm using the version in the Chrome store. I'll try to fix it myself, but I thought I'd let you know in the meantime.

**Comment by kennethgillen** [comment]
I see the same.  Slightly different ordering for reference:

When setting up:
`donut --> donut life`

I expect 
`donut --> donut life`
but I see
`donut --> donut life life`

**Comment by jkingsman** [comment]
Hm that's interesting... To be honest, I haven't touched this project in years, and I'm swamped with work right now -- feel free to make a PR and I'll update the store version, though!

**Comment by djedi** [comment]
Yeah, I see the same. I have something like this...

`^$.+` --> `$& ndone`

So it would take a string like

`$ some-command`

and output 

`$ some-command ndone ndone`

**Comment by jkingsman** [comment]
I've submitted @djedi's patch that should fix this to the dev store; update should be out to y'all in a couple hours or so. @djedi, once you're on `0.0.2`, could you confirm your behavior is resolved?

Thanks!

**Comment by subflux** [comment]
Nice on @djedi - thanks!

**Comment by djedi** [comment]
Yeah, it works for me. Thanks!

**Comment by jkingsman** [comment]
Awesome! Glad to hear it 🙂
