### ISSUE TITLE
Replace HTML

### ISSUE THREAD

**Issue by Rosetux** [jkingsman/regex-replace#4]
Hello,

I would like to be able to replace an URL by another (to do image replacement).

Is there a way to parse the entire DOM and not just the text nodes ?

**Comment by jkingsman** [comment]
Hypothetically, yes, but that can get dangerous if you start accidentally replacing text in tags and that sort of thing. Unless you can think of a neat way of working into the current flow non-disruptively, I think that feature may be off the roadmap for a while.
